"""MacPilot 的集中配置。"""

from __future__ import annotations

import os
from pathlib import Path


APP_NAME = "MacPilot"
HOST = "127.0.0.1"
PORT = 8737

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_ROOT / "web"
DATA_DIR = Path(os.environ.get("MACPILOT_DATA_DIR", "~/.macpilot")).expanduser()
DB_PATH = Path(os.environ.get("MACPILOT_DB_PATH", DATA_DIR / "data.db")).expanduser()

SAMPLE_INTERVAL_SECONDS = 3
SLOW_SAMPLE_TICKS = 20
SLOW_SAMPLE_INTERVAL_SECONDS = SAMPLE_INTERVAL_SECONDS * SLOW_SAMPLE_TICKS
CLEANUP_INTERVAL_SECONDS = 60 * 60
WEBSOCKET_INTERVAL_SECONDS = 3

METRICS_RETENTION_SECONDS = 48 * 60 * 60
PROCESS_RETENTION_SECONDS = 7 * 24 * 60 * 60
DISK_RETENTION_SECONDS = 90 * 24 * 60 * 60
EVENT_RETENTION_SECONDS = 90 * 24 * 60 * 60
EVENT_DEDUP_SECONDS = 30 * 60

CPU_HIGH_PERCENT = 85.0
CPU_HIGH_DURATION_SECONDS = 3 * 60
MEM_HIGH_PERCENT = 90.0
SWAP_GROWTH_BYTES = 2 * 1024**3
SWAP_WINDOW_SECONDS = 10 * 60
DISK_WARNING_PERCENT = 90.0
DISK_CRITICAL_PERCENT = 95.0
NET_SPIKE_MIN_BPS = 10 * 1024**2
NET_SPIKE_MULTIPLIER = 10.0
NET_SPIKE_DURATION_SECONDS = 2 * 60
NET_BASELINE_SECONDS = 60 * 60

PROCESS_SNAPSHOT_LIMIT = 15
NETTOP_TIMEOUT_SECONDS = 5
SEARCH_TIMEOUT_SECONDS = 10
LARGE_FILE_TIMEOUT_SECONDS = 30
MAX_CHART_POINTS = 500

DEFAULT_DISK_MOUNTS = ("/", "/System/Volumes/Data")

